### ISSUE TITLE
Fix emoji chart tofu

### ISSUE THREAD

**Issue by nedley** [unicode-org/unicodetools#95] opened 2021-07-15 00:02 UTC
Charts like https://unicode.org/emoji/charts-14.0/emoji-released.html use U+1F3FF to denote a skin-tone modifier, but it seems to be rendered as tofu by Chrome.

**Comment by markusicu** [comment] 2022-08-17 21:32
Could this be caused by whatever font is set in the styles/CSS? In https://github.com/unicode-org/cldr/blob/main/common/collation/root.xml `& [last primary ignorable]<<*🦰🦱🦳🦲🏻🏼🏽🏾🏿` it shows up fine on a browser that shows tofu on the emoji chart page.

Ned thinks it might have to do with what character precedes it.

Might be safest to just use an embedded color swatch image.

**Comment by josh-hadley** [comment] 2022-08-18 16:05
I wonder if some minor modifications to the CSS might fix this? I tried hacking/overriding the resolved `font-family` in Chrome (Mac), adding `'Apple Color Emoji'` at the end on one of the places this happens, and that seemed to do the trick. See attached screen captures. It would be nice not to have to embed an image if it can be avoided.

![before](https://user-images.githubusercontent.com/51727949/185441725-5eb34329-3595-4a0c-b459-41edb480711f.png)
![after](https://user-images.githubusercontent.com/51727949/185441740-3d1076dd-4f9c-4e54-8dff-5612f9ba4748.png)

**Comment by nedley** [comment] 2022-08-18 16:33
The problem is that this appears to be a cross-platform issue with Chrome, so I would like to avoid platform-specific fixes if at all possible. And if it requires a color swatch I would use pure CSS rather than an image.

**Comment by josh-hadley** [comment] 2022-08-18 17:04
Understood and I agree it would be better to do something that isn't platform-specific (_and_ is not an image).

I did a little more tinkering and it does indeed look like its the preceding character that triggers this. Actually, looks like _any_ preceding character that is not also an emoji. It seems like once Chrome gets a "hit" in the font fallback scheme, it stops falling back and uses the last font found to render the remainder of the string within the same block-level (?) element. So for example, `<p>&#x1F3ff;</p>` will render fine, but `<p>a &#x1F3ff;</p>` will fail on the skintone character because it tries to use the same font that it found for `a`. Similarly, `<div><span>a &#x1F3ff;</span><span>&#x1F3ff;</span></div>` fails on both because they're in the same block-level element (outer `<div>`). So for the example I used in the screen captures above, it wouldn't be fixed by simply moving the skintone character out of the `<span>`. It would need to be moved to a new `<div>` or other block-level element.

As to fixing it with pure CSS, I assume you mean something like a `<div>` with fixed size + color fill (and maybe border)? Would that work inside of the `<span>`s on that page?

**Comment by nedley** [comment] 2022-08-18 17:30
Replacing the U+1F3FF with something like `<div style="display:inline-block; vertical-align:middle; height:12px; width:12px; background-color:brown;">&nbsp;</div>` seems promising. @josh-hadley Would you be interested in refining this approach, perhaps with a better color and border?

**Comment by nedley** [comment] 2022-08-18 17:32
Better yet, `<div style="display:inline-block;">&#x1F3ff;</div>` seems to do the trick.

**Comment by josh-hadley** [comment] 2022-08-18 17:33
That might be better as I thought I remembered that putting block-level elements (plain `<div>`) inside of inline elements (`<span>`) was a no-no. But using `display:inline-block` might be the way to work around. I can tinker some more on that.

**Comment by josh-hadley** [comment] 2022-08-18 21:50
I played around with this some and I think the following is what needs to happen:
1) define a new CSS style something like:
```
.sk5 {display: inline-block;}
```
2) in the chart code, move *only* the skintone emoji character (U+1F3FF) into its own *`<span>`* (not `<div>`) with `class="sk5"` like:
```
<p>The count of new variants is in the Other Keywords column, such as “➕ 5 Ⓒ ‧ <span class="sk5">🏿</span>”.  ...</p>
```
and
```
<div class="comment">➕ 5 <span title="singleton + skin">Ⓒ ‧ </span><span class="sk5">🏿</span></div>
```

That seemed to work well for me for the cases in `emoji-released.html`.

**Comment by nedley** [comment] 2022-08-18 22:22
Excellent, thanks! I will be shoehorning that in shortly.

**Comment by nedley** [comment] 2022-08-18 23:54
Okay, I think I found the room where it happens. I’m leaning towards using an inline style, though, since in my mind the workaround is a self-contained “token” and I’m not sure what benefit there is to a new class.

**Comment by josh-hadley** [comment] 2022-08-18 23:56
I was just thinking it would save some bytes versus an inline style for each place it's needed (plus make it easier to modify if other tweaks are needed) but I guess it's generated anyway so maybe that doesn't save much.

**Comment by nedley** [comment] 2022-08-19 00:37
Fair point. I’m trying to localize the fix to avoid code duplication, if not tag duplication.

**Closed** 2022-08-19 01:50 UTC

**Comment by markusicu** [comment] 2022-08-19 17:52
Please remember to post the new chart so that Rick & Ken can pick it up.

**Comment by nedley** [comment] 2022-08-19 18:07
This will be rolled into the 15.0 charts.
